on: push
  
name: tst
jobs:
  tst:        
    name: Deploy via FTP	
    runs-on: ubuntu-latest	
    steps:
      - name: damn
        continue-on-error: true
        run: exit 1

      - name: print
        run: echo here
