on: push
  
name: tst
jobs:
  tst:        
    name: Deploy via FTP	
    runs-on: ubuntu-latest	
    outputs:
      lib: ${{ steps.filter.outputs.lib }}
      pages: ${{ steps.filter.outputs.pages }}
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: print
        run: echo ${{ github.ref }}

      - name: Check 
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            lib:
              - 'lib/**'
            pages:
              - 'pages/**'

      - name: Lib
        if: ${{ steps.filter.outputs.lib == 'true' }}
        run: echo ${{ steps.filter.outputs.lib }}

      - name: Pages
        if: ${{ steps.filter.outputs.pages == 'true' }}
        run: echo ${{ steps.filter.outputs.pages }}

  run:        
    name: RR	
    needs: tst
    if: ${{ needs.tst.outputs.lib == 'true' || needs.tst.outputs.pages == 'true' }}
    runs-on: ubuntu-latest	
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Lib
        if: ${{ needs.tst.outputs.lib == 'true' }}
        run: echo ${{ needs.tst.outputs.lib  }}

      - name: Pages
        if: ${{ needs.tst.outputs.pages == 'true' }}
        run: echo ${{ needs.tst.outputs.pages }}