on: push
  
name: tst
jobs:
  tst:        
    name: Deploy via FTP	
    runs-on: ubuntu-latest	
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Check 
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            lib:
              - 'lib/**'
            pages:
              - 'pages/**'

      - name: Lib
        if: ${{ steps.filter.outputs.lib == 'true' }}
        run: echo ${{ steps.filter.outputs }}

      - name: Pages
        if: ${{ steps.filter.outputs }}
        run: echo ${{ steps.filter.outputs }}
